baseurl = "http://rr-visual-design.github.io/"
languageCode = "en-us"
title = "Radford Visual Design"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Nick Radford"
	description = ""

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Radford Visual Design"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Fresh, full-service design for the marching arts"
		subtitle   = "Radford Visual Design brings you high quality program and visual design, and in-person education for the marching and pageantry arts."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = '<p class="text-faded quote">&ldquo;Nick brings clear vision, commitment to cohesive design, modern approach and a love for and natural ability to inspire students. With Radford Visual Design, you are getting great, innovative design AND the instructional expertise required to bring his personal artistic vision to fruition. I would recommend him without hesitation.&rdquo;</p>
                <p class="quote-author">&mdash; Jacob Hartman - Marion Harding High School, OH</p>'
		buttonText  = "View Services"
    link        = "#services"



	# Service section
	[params.services]
		headline = "At your service"

    [[params.services.list]]
        icon = "fa-dot-circle-o"
        title = "Drill and Visual Design"
        description = "Unique drill and visual design to help you stand out amongst the competition."

    [[params.services.list]]
				icon = "fa-flag"
				title = "Color Guard Design"
				description = "From introductory to world-class, taught hands-on or by video. Flag, rifle, sabre."

		[[params.services.list]]
        icon = "fa-file-image-o"
        title = "Graphic Design"
        description = "Need graphics for social media, flyers, or to print for on-field scrims? We can do that."

    [[params.services.list]]
        icon = "fa-heart"
        title = "Made with Love"
        description = "We love what we do, and look forward to bringing something new to your ensemble!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Like what you see? Contact us below!"

		[params.aside.button]
			text = "Contact Us"
			link = "#contact"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with Radford Visual Design? That's great! Give us a call or send us an email and we'll get back to you as soon as possible!"
		phone = "(415) 851-0846"
		email = "hello@rrvisual.design"
